[package]
name = "starmedia_natives"
version = "0.1.0"
edition = "2024"
authors = [ "asojidev", "AlsoSylv", "BluSpring" ]
license = "LGPL-3"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"

[dependencies.windows]
version = "0.61.3"
features = [
    "Foundation_Collections",
    "Media_Control",
    "Storage_Streams",
]

[profile.release]
opt-level = "z"
lto = true
debug = true